# Generated by Django 5.1.7 on 2025-03-26 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('verification_token', models.CharField(max_length=100, unique=True)),
                ('verification_token_expiry', models.DateTimeField()),
                ('verification_method', models.CharField(blank=True, choices=[('dns', 'DNS Record'), ('file', 'File Upload'), ('meta_tag', 'Meta Tag')], max_length=10, null=True)),
                ('verification_proof', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('ownership', 'Ownership Verification'), ('health', 'Health Check'), ('capabilities', 'Capabilities Check'), ('security', 'Security Assessment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='verification.verificationrequest')),
            ],
            options={
                'ordering': ['check_type'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_up', models.BooleanField()),
                ('response_time', models.FloatField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['server', '-created_at'], name='verificatio_server__79f564_idx'), models.Index(fields=['is_up'], name='verificatio_is_up_22226e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['server', 'status'], name='verificatio_server__86fcbd_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['verification_token'], name='verificatio_verific_96cf33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verificationcheck',
            unique_together={('verification_request', 'check_type')},
        ),
    ]
