# Generated by Django 5.1.7 on 2025-03-26 00:25

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_servers', models.PositiveIntegerField(default=0)),
                ('active_servers', models.PositiveIntegerField(default=0)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('unique_clients', models.PositiveIntegerField(default=0)),
                ('new_servers', models.PositiveIntegerField(default=0)),
                ('agent_count', models.PositiveIntegerField(default=0)),
                ('resource_count', models.PositiveIntegerField(default=0)),
                ('tool_count', models.PositiveIntegerField(default=0)),
                ('top_tags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Network analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClientTrafficLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('servers_accessed', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('top_capabilities', models.JSONField(blank=True, default=dict)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='analytics_c_date_734998_idx'), models.Index(fields=['client_id', '-date'], name='analytics_c_client__a8d21f_idx')],
                'unique_together': {('client_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
                ('capability', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time_ms', models.FloatField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('is_error', models.BooleanField(default=False)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='servers.server')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['server', '-timestamp'], name='analytics_r_server__2464b1_idx'), models.Index(fields=['server', 'client_id'], name='analytics_r_server__edc051_idx'), models.Index(fields=['server', 'capability'], name='analytics_r_server__4fe1db_idx'), models.Index(fields=['server', 'is_error'], name='analytics_r_server__4b9271_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServerAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('unique_clients', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('status_2xx', models.PositiveIntegerField(default=0)),
                ('status_3xx', models.PositiveIntegerField(default=0)),
                ('status_4xx', models.PositiveIntegerField(default=0)),
                ('status_5xx', models.PositiveIntegerField(default=0)),
                ('top_capabilities', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='servers.server')),
            ],
            options={
                'verbose_name_plural': 'Server analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['server', 'date'], name='analytics_s_server__b5b06f_idx')],
                'unique_together': {('server', 'date')},
            },
        ),
    ]
